print("hello world")
#THINGS DONE ON DAY 1;
# 1. LEARNED HOW TO CREATE AND REPOSITORIES, INSTALL EXTENSIONS TO VSCODE, REFRESHED ON THE BASICS OF PYTHON.
# 2. CREATED A PLAN/GOALS FOR THE NEXT 60 DAYS
# 3. --- PLANNED OUT DAY 2
